Repository TalesOfSpaceStationsRep/TOSS14, pull requests merged in 2025-03, with the labels that each got.

#4 [FIX] Фикс локализации
  Content.Shared/Localizations/ContentLocalizationManager.cs
Labels: S: Untriaged, size/S

#5 [FIX] Фикс системы имён
  Content.Shared/Preferences/HumanoidCharacterProfile.cs
Labels: S: Untriaged, size/XS

#6 [FIX] Разрешение экрана
  Content.Shared/CCVar/CCVars.Viewport.cs
Labels: S: Untriaged, size/XS

#7 [ADD] Броня и мечи
  Resources/Prototypes/TOSS14/Datasets/tags.yml
  Resources/Prototypes/TOSS14/Entities/Clothing/Belt/belts.yml
  Resources/Prototypes/TOSS14/Entities/Clothing/OuterClothing/armor.yml
  Resources/Prototypes/TOSS14/Entities/Objects/Weapons/Melee/Swords.yml
  Resources/Textures/TOSS14/Clothing/OuterClothing/Armor/lightknight.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/TOSS14/Clothing/OuterClothing/Armor/lightknight.rsi/icon.png
  Resources/Textures/TOSS14/Clothing/OuterClothing/Armor/lightknight.rsi/meta.json
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Palash.rsi/icon.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Palash.rsi/inhand-left.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Palash.rsi/inhand-right.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Palash.rsi/meta.json
  Resources/Textures/TOSS14/Objects/Weapons/Melee/RicardoRapire.rsi/icon.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/RicardoRapire.rsi/inhand-left.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/RicardoRapire.rsi/inhand-right.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/RicardoRapire.rsi/meta.json
  Resources/Textures/TOSS14/Objects/Weapons/Melee/SunlightStraightSword.rsi/icon.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/SunlightStraightSword.rsi/inhand-left.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/SunlightStraightSword.rsi/inhand-right.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/SunlightStraightSword.rsi/meta.json
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Uthiganata.rsi/icon.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Uthiganata.rsi/inhand-left.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Uthiganata.rsi/inhand-right.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Uthiganata.rsi/meta.json
Labels: Changes: Sprites, size/M, Changes: No C#

#8 [ADD] Фикс спрайтов и новое оружие
  Resources/Prototypes/TOSS14/Entities/Objects/Weapons/Melee/Swords.yml
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Palash.rsi/inhand-left.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Palash.rsi/inhand-right.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Shortsword.rsi/icon.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Shortsword.rsi/inhand-left.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Shortsword.rsi/inhand-right.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Shortsword.rsi/meta.json
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Steelrapire.rsi/icon.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Steelrapire.rsi/inhand-left.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Steelrapire.rsi/inhand-right.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Steelrapire.rsi/meta.json
  Resources/Textures/TOSS14/Objects/Weapons/Melee/SunlightStraightSword.rsi/inhand-left.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/SunlightStraightSword.rsi/inhand-right.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Uthiganata.rsi/inhand-left.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Uthiganata.rsi/inhand-right.png
Labels: Changes: Sprites, Changes: No C#, size/S

#14 [fix]Новые спрайты
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Palash.rsi/icon.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/RicardoRapire.rsi/icon.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Shortsword.rsi/icon.png
  Resources/Textures/TOSS14/Objects/Weapons/Melee/Uthiganata.rsi/icon.png
Labels: Changes: Sprites, Changes: No C#
